trigger:
  branches:
    include:
      - main

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: UseNode@2
    displayName: 'Install Node.js'
    inputs:
      version: '14'
      checkLatest: true
  - run: npm ci
  - run: npm run lint
  - run: npm run prettier
  - run: npm run build
  - task: ArchiveFiles@2
    displayName: 'Archive build artifacts'
    inputs:
      rootFolderOrFile: 'build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish pipeline artifact'
    inputs:
      artifactName: 'build'
      targetPath: '$(Build.ArtifactStagingDirectory)/build.zip'

