trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '14'
      checkLatest: true
      cachePath: 'npm'
  - script: |
      npm ci
    displayName: 'Install Dependencies'
  - script: |
      npm run lint
      npm run prettier
    displayName: 'Run ESLint & Prettier'
  - script: |
      npm run build
    displayName: 'Build'
  - script: |
      npm start &
      npm run cypress
    displayName: 'Run Cypress'
