trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '14'
      checkLatest: true
      cachePath: 'npm'
  - script: |
      npm ci
    displayName: 'Install Dependencies'
  - script: |
      npm run lint
      npm run prettier
    displayName: 'Run ESLint & Prettier'
  - script: |
      npm run build
    displayName: 'Build'
  - task: ArchiveFiles@2
    displayName: 'Archive Files'
    inputs:
      rootFolderOrFile: 'build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: $(Build.ArtifactStagingDirectory)/build.zip
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/build.zip'
      artifact: 'build'

#test
